Homework-Dagger2 Нимас Ксения
Otus-Android/Dagger2Homework pull request #111
Opened 2024-02-11 03:36 UTC by Konkordia17

2024-02-11 09:30 UTC, antonkazakov requested changes
Привет. Оставил пару комментариев

2024-02-11 09:30 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +@Qualifier @Retention(AnnotationRetention.RUNTIME) annotation class ApplicationContext
Retention(AnnotationRetention.RUNTIME) можно убрать, это нужно для инсрументов которые в рантайме зависимости провайдят

2024-02-11 09:30 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +    private val context: Context,
Здесь будет утечка активити, либо нужно через слабые ссылки работать либо не наследовать от ViewModel

2024-02-11 09:30 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +class ViewModelReceiver(private val context: Context, private val stateObserver: StateObserver) :
Нужно сюда запровайдить иммутабельную версию StateObserver, чтобы я не мог эмитить из класса-читателя

2024-02-12 03:17 UTC, Konkordia17 commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +@Qualifier @Retention(AnnotationRetention.RUNTIME) annotation class ApplicationContext
убрала

2024-02-12 03:23 UTC, Konkordia17 commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +    private val context: Context,
поправила

2024-02-12 03:47 UTC, Konkordia17 commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +class ViewModelReceiver(private val context: Context, private val stateObserver: StateObserver) :
сделано

2024-02-18 09:39 UTC, closed without merging