Homework Dagger2
Otus-Android/Dagger2Homework pull request #117
Opened 2024-03-01 07:43 UTC by LexAndro3723

Homework Dagger2

2024-03-12 10:34 UTC, antonkazakov requested changes
Привет. Оставил несколько вопросов/замечаний

2024-03-12 10:34 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/DaggerAnnotations.kt
> +@Retention(AnnotationRetention.RUNTIME)
Можно убрать. Тебе в рантайме они не нужны. Все аннотации на стадии компиляции будут процессится

2024-03-12 10:34 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducerModule.kt
> +    @FragmentScope
Нужен ли скоуп?

2024-03-12 10:34 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    _colorFlow: MutableStateFlow<Color>,
Хочется чтобы в ресивере не было возможности события эмитить

2024-03-12 10:34 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +    @ActivityContextQualifier private val context: Context
Решение по инжекту ВМ через мультибиндинг норм, но проблема в том что если здесь будет андроидовская вьюмодель то у тебя будет утечка активити, ведь ВМ дольше живет. Либо нужно тебе убрать наследование либо например через викреференсы попробовать

2024-03-22 14:13 UTC, LexAndro3723 commented
> Привет. Оставил несколько вопросов/замечаний
переделал

2024-03-22 14:14 UTC, LexAndro3723 commented
Переделал

2024-04-02 17:07 UTC, closed without merging