Реализовал приложение с использованием Dagger 2
Otus-Android/Dagger2Homework pull request #121
Opened 2024-05-09 11:04 UTC by Ra53n

2024-05-18 08:57 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-05-18 08:57 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +    fun bindContext(application: Application): Context
Этот биндс разве нужен?

2024-05-18 08:57 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/MainActivityComponent.kt
> +    @Named("applicationContext")
Если у тебя два типа и один размечен квалифаером/неймед то в целом второй можно не размечать. Даггер поймет)

2024-05-18 08:57 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val flow: MutableStateFlow<Int>
Хотелось бы чтобы в ресивере не было возможности эмитить события во флоу

2024-05-18 08:57 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Из-за этого может быть утечка памяти. Нужно продумать тогда как работать с активити. Ведь сейчас у тебя ВМ будет держать ссылку на старую активити

2024-05-20 13:56 UTC, Ra53n commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +    fun bindContext(application: Application): Context
Нет, не нужен. Убрал

2024-05-20 13:57 UTC, Ra53n commented on app/src/main/java/ru/otus/daggerhomework/MainActivityComponent.kt
> +    @Named("applicationContext")
Убрал один квалифаер

2024-05-20 13:57 UTC, Ra53n commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val flow: MutableStateFlow<Int>
Исправил

2024-05-20 13:57 UTC, Ra53n commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Вынес контекст из вью модели

2024-05-25 12:38 UTC, antonkazakov reviewed
👍

2024-05-25 12:39 UTC, closed without merging