dagger 2 homework
Otus-Android/Dagger2Homework pull request #122
Opened 2024-05-11 08:53 UTC by evtyryshkin

2024-05-18 09:08 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-05-18 09:08 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ColorStorageRepository.kt
> +class ColorStorageRepositoryImpl @Inject constructor() : ColorStorageRepository {
Я думаю что это не совсем репозиторий, все таки совсем другая ответственность у класса

2024-05-18 09:08 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ColorStorageRepository.kt
> +interface ColorStorageRepository {
Нужно его разбить на 2 интерфейса. Аналогиско mutableflow/flow mutablelivedata/livedata.
Иначе у тебя сейчас есть возможность эмитить из ресивера

2024-05-18 09:08 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +    lateinit var viewModel: ViewModelProducer
1. Недавно говорили на лекциях что нельзя ни в коему случае инжектить VM напрямую, хилт даже компайл тайм ошибку кинет
2. В этой работе если унаследоваться от VM из jetpack, то нужно как то обрабатывать ситуацию в которой у тебя ссылка на активити держится во вьюмодели

2024-05-18 09:08 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    fun provideActivityContext(): Context
При желании можно оставить 1 квалифаер. Если в графе есть 2 одинаковых типа, один из которых помечен Named/Qualifier, то второй можно оставить без него

2024-05-19 07:09 UTC, evtyryshkin commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    fun provideActivityContext(): Context
Это я знаю, но так более наглядно выходит. Оставлю так

2024-05-19 09:09 UTC, evtyryshkin commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +    lateinit var viewModel: ViewModelProducer
1) Хм, действительно так, прочитал дополнительно почему обязательно нужно создавать через Provider. Был пробел  в знаниях связанный с этим. Спасибо!
2) Про второй коммент немного не понял. Я же итак наследуюсь от вьюмоделей из jetpack вроде бы.

2024-05-25 12:37 UTC, closed without merging