Ready!
Otus-Android/Dagger2Homework pull request #124
Opened 2024-05-15 06:10 UTC by SergeyGaldin

2024-05-18 09:27 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-05-18 09:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/annotations/StateFlowColor.kt
> +annotation class StateFlowColor
Зачем нужен этот квалифаер?

2024-05-18 09:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/components/FragmentComponent.kt
> +interface FragmentComponent {
На каждый фрагмент нужно делать разные компонент, у тебя в них разные сущности нужны

2024-05-18 09:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/components/MainActivityComponent.kt
> +    fun provideViewModelProducer(): ViewModelProducer
Почему они в активити компоненте?

2024-05-18 09:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/components/MainActivityComponent.kt
> +    fun provideActivityContext(): Context
Если у тебя есть 2 одинковых типа в графе, то достаточно пометить квалифаером один. Даггер поймет

2024-05-21 05:31 UTC, SergeyGaldin commented on app/src/main/java/ru/otus/daggerhomework/di/annotations/StateFlowColor.kt
> +annotation class StateFlowColor
По сути он не нужен, он для ясности кода, что бы было понятно, что несет в себе этот флоу

2024-05-25 12:45 UTC, closed without merging