Dagger2 HM
Otus-Android/Dagger2Homework pull request #125
Opened 2024-05-15 22:24 UTC by EdKrupenin

2024-05-18 09:32 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-05-18 09:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/MainActivity.kt
> +            eventObserver = EventObserver(),
А почему ты его прокидываешь, его же можно через фабрику даггеру создать?

2024-05-18 09:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/Qualifier.kt
> +annotation class ActivityContext
Тут в целом достаточно одного квалифаера на контекст

2024-05-18 09:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/module/ProducerModule.kt
> +        @Provides
Лучше заменить на binds

2024-05-18 09:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/module/ReceiverModule.kt
> +    companion object {
А зачем тебе вложенность, просто сделай ReceiverModule object'ом

2024-05-22 12:59 UTC, EdKrupenin commented on app/src/main/java/ru/otus/daggerhomework/di/module/ProducerModule.kt
> +        @Provides
Понял, сделал, можно пару слов почему так лучше? что бы даггер не создавал экземпляр в общекте?

2024-05-25 12:39 UTC, closed without merging