dagger homework
Otus-Android/Dagger2Homework pull request #126
Opened 2024-05-19 20:43 UTC by Dmitry374

Dagger homework

2024-06-02 07:52 UTC, antonkazakov requested changes
Привет. Оставил комментарии

2024-06-02 07:52 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/activityMain/MainActivityModel.kt
> +object MainActivityModel {
А зачем нужен этот модуль?

2024-06-02 07:52 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/annotation/ActivityContext.kt
> +@Retention(AnnotationRetention.RUNTIME)
Можно убрать. Они не процессятся в рантайме

2024-06-02 07:52 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/application/AppModule.kt
> +    companion object {
Это нужно убрать

2024-06-02 07:52 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val colorEventSource: ColorEventSource,
Нужно разделить ColorEventSource на 2 типа. Иммутабельный и мутабельный. Чтобы в ресивере ты не мог отправлять события

2024-06-15 22:11 UTC, Dmitry374 commented on app/src/main/java/ru/otus/daggerhomework/di/activityMain/MainActivityModel.kt
> +object MainActivityModel {
Да, не нужен. Убрал

2024-06-15 22:11 UTC, Dmitry374 commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val colorEventSource: ColorEventSource,
Разделил на ColorReceiver и ColorProducer

2024-07-02 08:01 UTC, closed without merging