Robilko/dagger_homework
Otus-Android/Dagger2Homework pull request #127
Opened 2024-05-21 00:55 UTC by Robilko

2024-06-02 08:12 UTC, antonkazakov requested changes
Привет. Оставил комменты

2024-06-02 08:12 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +@Retention(AnnotationRetention.RUNTIME)
Можно убрать, она не нужна в рантайме

2024-06-02 08:12 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val eventObserver: EventObserver,
Нужно разделить EventObserver на мутабельный и иммутабельный, чтобы не было возможности из приемника эмитить события

2024-06-02 08:12 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Не нужно их наследовать от androidx.lifecycle.ViewModel - будет утечка активити

2024-06-03 09:12 UTC, Robilko commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +@Retention(AnnotationRetention.RUNTIME)
убрал везде

2024-06-03 09:13 UTC, Robilko commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
убрал наследование

2024-06-15 12:05 UTC, antonkazakov reviewed
👍

2024-06-15 12:06 UTC, closed without merging