Создано дерево компонентов
Otus-Android/Dagger2Homework pull request #128
Opened 2024-05-21 16:43 UTC by firkatdavletov

2024-06-02 08:24 UTC, antonkazakov requested changes
Привет! Оставил комментарии

2024-06-02 08:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/App.kt
> +    val component by lazy { DaggerApplicationComponent.factory().create(this) }
Потокобезопасный лейзи здесь не нужен

2024-06-02 08:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +    val component by lazy {
Здесь тоже

2024-06-02 08:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val appObserver: AppObserver
Нужно сюда инжектить иммутабельную версию. Чтобы не было возможности эмитить

2024-06-02 08:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +): ViewModel() {
Нельзя тут наследоваться от ViewModel т.к. будет утечка памяти из-за ссылки на активити

2024-06-12 06:58 UTC, AgentTC commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +    val component by lazy {
В чем минусы такого подхода?

2024-06-12 07:00 UTC, firkatdavletov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +    val component by lazy {
Выше мой комментарий, с другого аккаунта)

2024-07-02 08:00 UTC, closed without merging