Dagger 2 home work
Otus-Android/Dagger2Homework pull request #133
Opened 2024-06-25 19:40 UTC by St1ve

2024-07-09 18:24 UTC, antonkazakov requested changes
Привет. Отличная работа, оставил пару комментов

2024-07-09 18:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Ты все правильно организовал по инжекту VM, но тут будет проблема что VM живет дольше чем активити и держит ссылку на нее. Лучше убрать наследование

2024-07-09 18:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/qualifiers/ActivityContext.kt
> +@Retention(RUNTIME)
Можно убрать, в рантайме они не нужны

2024-07-13 08:06 UTC, St1ve commented
Спасбо за комментарии. Сделал правки. 

Также перенес создание activityComponent перед onCreate, чтобы не было проблемы при смене конфигурации

2024-07-24 16:45 UTC, closed without merging