Homework dagger (Subcomponents)
Otus-Android/Dagger2Homework pull request #139
Opened 2024-08-10 12:00 UTC by bmv-2143

### Реализуйте ApplicationComponent
Это корень нашего дерева компонентов. Инициализируется в классе App, прокидывает в граф через Component Dependencies/Subcomponents ниже по графу следующие сущности:
- Context(Application) до FragmentProducerComponent и FragmentReceiverComponent. 
Проброс Context в граф реализуйте через BindsInstance + ComponentFactory

### Реализуйте MainActivityComponent
Инициализируется в MainActivity. Прокидывает следующие сущности:
- Context(Activity). Проброс в граф реализуйте через BindsInstance + ComponentFactory
- Ваша реализация обсервера(Coroutine Channel/StateFlow/Subject либо другую реализацию обсервера). Он понадобится нам чтобы отправлять евенты из одного фрагмента и принимать их в другом, в обоих фрагментах должен быть один и тот же инстанс обсервера.

### Реализуйте FragmentReceiverComponent/FragmentProducerComponent
Коммуникацию между Producer и Receiver осуществите через канал/StateFlow/Subject либо другую реализацию обсервера которая уже есть в графе. ViewModelProducer должна отправлять эвенты, ViewModelReceiver должна получать эвенты. Обсерверы должны прокидываться в конструкторы вьюмоделей и существовать в единственном экземпляре в Activity.
Флоу отправки эвента выглядит следующим образом:
Клик на кнопку button в FragmentProducer -> вызов метода вьюмодели -> проброс евента в обсервер -> евент ловится на стороне ViewModelReceiver -> евент передается FragmentReceiver и вызывается функция ru.otus.daggerhomework.FragmentReceiver#populateColor

2024-08-27 04:51 UTC, antonkazakov requested changes

2024-08-27 04:51 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/presentation/ViewModelReceiver.kt
> +    private val colorObserver: ColorObserver
Сюда лучше эмитить иммутабельную версию, тоесть ту что не может эмитить события. попоробуй через даггер это решить

2024-08-28 10:48 UTC, bmv-2143 commented on app/src/main/java/ru/otus/daggerhomework/presentation/ViewModelReceiver.kt
> +    private val colorObserver: ColorObserver
Исправил. Вынес из `ColorObserver` интерфейс `ReadOnlyColorObserver`, который теперь используется во ViewModelReceiver.
Биндинг интерфейса к имплементации осущетвляется во `FragmentsModule`.

2024-09-14 11:54 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/FragmentReceiverComponent.kt
> +interface ReceiverModule
Правила нет, но кажется так гораздо удобнее, представь что у тебя их не 2 а 20, придется 20 модулей делать, либо один)

2024-09-14 11:54 UTC, closed without merging