Dagger2Homework
Otus-Android/Dagger2Homework pull request #21
Opened 2021-11-29 22:06 UTC by babushkinanatoly

2021-12-12 13:30 UTC, antonkazakov requested changes
Прокинь пожалуйста app context через App -> Activity -> Fragment

2021-12-12 13:30 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/producer/FragmentProducerComponent.kt
> +        ApplicationComponent::class,
А почему ты не сделал MainActivityComponent зависимым от ApplicationComponent. Транзитивно там появился бы app context

2021-12-18 10:31 UTC, babushkinanatoly commented on app/src/main/java/ru/otus/daggerhomework/producer/FragmentProducerComponent.kt
> +        ApplicationComponent::class,
Спасибо, поправил.

2022-01-27 19:02 UTC, antonkazakov commented
👍

2022-01-27 19:02 UTC, closed without merging