Dagger2 Homework
Otus-Android/Dagger2Homework pull request #22
Opened 2021-12-05 12:43 UTC by Infernno

2021-12-23 19:16 UTC, antonkazakov requested changes
Привет. Очень хочется поправить замечания по фабрике ВМ

2021-12-23 19:16 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/EventBus.kt
> +class EventBusImpl @Inject constructor() : EventBusReceiver, EventBusProducer {
Не совсем по теме Дз но почему ты тут не взял какой нибудь StateFlow?

2021-12-23 19:16 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/viewmodels/ViewModelReceiver.kt
> +    class Factory(
А фабрику не получится заинжектить?

2021-12-23 19:16 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ui/FragmentReceiver.kt
> +    lateinit var applicationContext: Context
Я думаю не совсем правильно инжектить во фрагмент, а потом вручную создавать фабрику. Часть преимуществ от использование DI теряем. Я думаю проще всего тебе фабрику сюда инжектить и потом достать ВМ

2022-01-15 10:10 UTC, Infernno commented
Поправил замечания и сделал одну фабрику которая инжектиться во фрагменты, ибо согласен, по отдельности все инжектить плохо.

Поменял еще `Channel `на `StateFlow`. Ради интереса эту штуку пробовал использовать.

2022-01-15 10:12 UTC, Infernno commented on app/src/main/java/ru/otus/daggerhomework/ui/FragmentReceiver.kt
> +    lateinit var applicationContext: Context
Поправил и сделал одну фабрику которая инжектиться во фрагменты, ибо согласен, по отдельности все инжектить и вручную собирать не очень хорошо.

2022-01-15 10:13 UTC, Infernno commented on app/src/main/java/ru/otus/daggerhomework/EventBus.kt
> +class EventBusImpl @Inject constructor() : EventBusReceiver, EventBusProducer {
Поменял `Channel` на `StateFlow`. Ради интереса `Channel` пробовал использовать.

2022-03-20 11:17 UTC, closed without merging