Home_work_4_Vb
Otus-Android/Dagger2Homework pull request #4
Opened 2021-08-17 12:30 UTC by VbiterGit

2021-10-04 06:38 UTC, antonkazakov requested changes

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiver.kt
> +            .create(MainActivityComponent.mainActivityComponentInstance!!, this.requireContext().applicationContext)
По заданию нужно сделать так чтобы Application Context попадал в граф из ApplicationComponent, в текущей реализации он не используется

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +class ViewModelReceiver @Inject constructor(
Здесь @Inject не нужна получается, мы же через конструктор создаем сами

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +@Retention(value = AnnotationRetention.RUNTIME)
Эта аннотация не нужна в даггере

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/FragmentReceiverComponent.kt
> +        fun provideViewModelReceiver(context: Context, mutableSharedFlow: MutableSharedFlow<Int>): ViewModelReceiver {
А зачем тебе этот метод? Мы же через фабрику создаем их

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    fun provideColorGenerator() : ColorGenerator
А зачем он тебе на уровне активити?

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    fun provideColorGenerator(): ColorGenerator {
Здесь лучше взять Binds

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    @ActivityScope
Я думаю здесь можно и без скоупа взять

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/FragmentReceiverComponent.kt
> +@Retention(AnnotationRetention.BINARY)
Можно без этой аннотации

2021-10-04 06:38 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/FragmentReceiverComponent.kt
> +    @ReceiverViewModel
А зачем тебе здесь квалифаер? у тебя же одна фабрика в этом компоненте

2021-10-07 12:38 UTC, VbiterGit commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +@Retention(value = AnnotationRetention.RUNTIME)
удалил

2021-10-07 12:38 UTC, VbiterGit commented on app/src/main/java/ru/otus/daggerhomework/di/FragmentReceiverComponent.kt
> +        fun provideViewModelReceiver(context: Context, mutableSharedFlow: MutableSharedFlow<Int>): ViewModelReceiver {
удалил. 

вроде понял, т.е. мы создаем фабрику, прокидываем ее через @Binds в компоненте, дальше во фрагменте инициализируем через инжект конкретный иннстанс нашей VM

2021-10-07 12:38 UTC, VbiterGit commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    fun provideColorGenerator(): ColorGenerator {
если меняю на @Binds rebuild сыпится, не пойму почему так:

error: [Dagger/MissingBinding] ru.otus.daggerhomework.ColorGeneratorImpl cannot be provided without an @Inject constructor or an @Provides-annotated method.

![image](https://user-images.githubusercontent.com/42649749/136384653-63e381b8-3ca5-4b68-a7f7-fd5bddd9204e.png)

2021-10-07 12:38 UTC, VbiterGit commented on app/src/main/java/ru/otus/daggerhomework/di/FragmentReceiverComponent.kt
> +@Retention(AnnotationRetention.BINARY)
удалил

2021-10-31 10:03 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    fun provideColorGenerator(): ColorGenerator {
Ну, собственно в логе все правильно написано) над `ColorGeneratorImpl` нет `Inject` аннотации, поэтому он не знает как создавать инстанс. В `Provides` методе ты сам вызываешь конструктор.

2021-10-31 10:03 UTC, antonkazakov commented
После правок все ок. Про ошибку при использовании binds ответил.

2021-10-31 10:03 UTC, closed without merging