Dagger2Homework from Pavel Scherbakov
Otus-Android/Dagger2Homework pull request #52
Opened 2022-09-04 15:38 UTC by PavelScherbakov

2022-09-26 05:27 UTC, antonkazakov requested changes
Привет, извини за задержку в проверке, оставил несколько замечаний, поправь пожалуйста

2022-09-26 05:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +sealed class Event {
А что здесь делает Event?)

2022-09-26 05:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +interface AppModule {
Можно сделать компонент без модулей

2022-09-26 05:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +): ViewModel() {
Я специально не наследовал от ViewModel, чтобы не утекал контекст активити)

2022-09-26 05:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ProducerComponent.kt
> +annotation class ProducerScope
А зачем тебе отдельные скоупы на ресивер и на продьюсер? Привязывайся лучше к компонентам андроида на уровне которых они живут

2022-09-26 05:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/MainActivityComponent.kt
> +    @EventObserver
А тут разве нельзя без квалифаера?

2022-09-26 05:27 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val eventObserver: MutableStateFlow<Event>,
Правильнее, конечно, чтобы у тебя здесь был иммутабельный StateFlow, это же Receiver

2022-10-02 06:33 UTC, PavelScherbakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +sealed class Event {
Перенёс Event в компонент активити. Видимо изначально обзервер на уровне app был.

2022-10-02 06:34 UTC, PavelScherbakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +interface AppModule {
Ок, убрал.

2022-10-02 07:55 UTC, PavelScherbakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val eventObserver: MutableStateFlow<Event>,
Поправил.

2022-10-02 09:21 UTC, PavelScherbakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +): ViewModel() {
По поводу утечки, непонятно почему она тут происходит, но вопрос больше в следующем:

А вообще с ViewModel как-то непонятно как правильно делать, есть противоречие.
С одной стороны, в условие задания обзервер должен находится в компоненте активити. Т.е. при смене конфигурации компонент активити будет пересоздаваться и соответственно обзервер тоже будет пересоздаваться.

С другой стороны, вьюмодель должна переживать смену конфигурации, по идее. Если мы используем андройдовский механизм создания вьюмодели через фабрику, то так и происходит - вью модель остаётся при смене конфигурации, но она остаётся со старым обзёрвером. Чтобы условия задачи выполнить, нельзя использовать андройдовский механизм создания вьюмодели. Хорошо, создаём вьюмодель используя di, но тогда вьюмодель будет пересоздаваться каждый раз при смене конфигурации (текущий вариан в задаче как раз сделан как на лекции было).

Противоречие в том, что и в задаче и на лекции вьюмодель пересоздаётся со сменой конфигурации, а для реальных приложениях этот вариант не подходит. Я видел на хабре вариант как делают, но сильно в нём не разбирался, не стал его применять в задаче, т.к это противоречит условию задачи, пришлось бы и обзервер выносить выше, типа на уровень приложения. Вообщем, вопрос для меня остался открытым, как правильно вью модели внедрять с помощью даггера.

Если сейчас я убераю наследование от ViewModel(), то получается вьюмодель можно инжектить без фабрики. И соответственно, она будет создаваться каждый раз при смене конфигурации (хотя сейчас она также создаётся каждый раз). Делать так?
А с утечкой контекста, получается, это из-за того что андройд у себя хранит эту вьюмодель вместе с контекстом, поэтому? Если мы не будем наследоваться от ViewModel(), то и утечки не будет?

2022-10-02 19:25 UTC, PavelScherbakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +): ViewModel() {
Сделал вариант без наследования от ViewModel()

2022-10-02 19:44 UTC, PavelScherbakov commented on app/src/main/java/ru/otus/daggerhomework/MainActivityComponent.kt
> +    @EventObserver
Так да, можно один контекст без квалифаера сделать, но раз явно выделили два контекста, то сделал два разных квалифаера.

2022-10-02 19:44 UTC, PavelScherbakov commented on app/src/main/java/ru/otus/daggerhomework/ProducerComponent.kt
> +annotation class ProducerScope
Если я скоуп не делаю, то ошибка:
ru.otus.daggerhomework.ProducerComponent (unscoped) cannot depend on scoped components:

2022-10-16 08:10 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +): ViewModel() {
Происходит она потому что у тебя в одну из вьюмоделей инжектиться Активити Контекст, а ВМ живет дольше чем активити, она умеет переживать пересоздание, соответсвенно у тебя ссылка на старую активити есть и старая не может быть собрана ГЦ. Если же ты делаешь просто класс который хранит ссылку на Активити, то он будет удален вместе с пересозданием активити -> пересозданием компонента

2022-10-16 08:11 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ProducerComponent.kt
> +annotation class ProducerScope
Все верно, но у тебя нет смысла для каждый ВМ/Активити/Фрагмент делать отдельный скоуп. Скоуп он делается на абстрактный компонент, например один скоуп на все Активити или один Скоуп на все парент фрагменты, но делать N скопов для каждого экрана неправильно

2022-10-16 08:12 UTC, antonkazakov commented
Привет. На вопросы ответил, работу засчитываю, но обрати внимание на скоупы

2022-10-16 08:12 UTC, closed without merging