ДЗ Dagger2 Аслапов Егор
Otus-Android/Dagger2Homework pull request #58
Opened 2022-11-13 18:17 UTC by aslapov

2022-11-26 18:35 UTC, antonkazakov requested changes
Привет. Пару замечаний оставил

2022-11-26 18:35 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
Здесь не нужно наследоваться от ViewModel. Утечка активити будет.
Но даже если бы было нужно, ты сделал неправильно инжект. Тебе нужно их создавать через фабрику а не инжектить напрямую в фрагменты

2022-11-26 18:35 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val colorFlow: MutableStateFlow<Int?>,
Не совсем верно, что ViewModelReceiver, класс который должен только принимать ивенты, имеет возможность их отправлять. Попробуй здесь положить иммутабельную версию

2022-11-29 18:09 UTC, aslapov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +) : ViewModel() {
наследование от ViewModel я уберу.
Но я все равно не очень понял почему нельзя инжектить напрямую во фрагмент? Вм все равно будет жить сколько и фрагмент...
И если создавать фабрику, то как это делается? иво фрагмент потом инжектится фабрика? не очень понимаю...

2022-11-29 18:11 UTC, aslapov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +    private val colorFlow: MutableStateFlow<Int?>,
Исправил (но еще не закоммитил) на StateFlow и все заработало.
Это здорово, что заработало, но не могу понять почему работает?)) - в MainActivityComponent у меня provision-метод на MutableStateFlow. Как даггер понимает, что где запрашивается StateFlow, нужно подставить MutableStateFlow?

2023-03-18 20:40 UTC, closed without merging