Dagger Homework
Otus-Android/Dagger2Homework pull request #59
Opened 2022-11-20 21:32 UTC by lewan42

2022-12-11 13:36 UTC, antonkazakov requested changes
Привет. Поправь пожалуйста замечания

2022-12-11 13:36 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewBindingFragment.kt
> +        view?.post {
Не по теме Дз, но зачем это нужно?

2022-12-11 13:36 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/main/MainActivity.kt
> +        activityComponent.inject(this)
а зачем тебе тут inject(this) если ты нрчего не инжектишь в активити?

2022-12-11 13:36 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/receiver/ViewModelReceiver.kt
> +    private val stateFlow: MutableStateFlow<Int>
Заинжекти сюда пожалуйста иммутабельную версию. Неправильно что ViewModelReceiver, который только слушает эвенты, имеет возможность эмитить их

2023-01-29 13:27 UTC, lewan42 commented on app/src/main/java/ru/otus/daggerhomework/ViewBindingFragment.kt
> +        view?.post {
захотел вью биндинг добавить для удобства, скопировал из другого проекта

2023-01-29 13:29 UTC, lewan42 commented on app/src/main/java/ru/otus/daggerhomework/main/MainActivity.kt
> +        activityComponent.inject(this)
думал, что это тоже нужно для построения графа

2023-01-29 13:29 UTC, lewan42 commented on app/src/main/java/ru/otus/daggerhomework/receiver/ViewModelReceiver.kt
> +    private val stateFlow: MutableStateFlow<Int>
согласен, поправил

2023-02-11 08:14 UTC, closed without merging