Dagger2Homework Vitaliy Farsiyan
Otus-Android/Dagger2Homework pull request #66
Opened 2022-12-26 14:04 UTC by Buzlighter

2022-12-26 14:10 UTC, Buzlighter commented
Переписал в процессе с subcomponents  на dependencies, так как 2ое решение более универсальное, плюс в решении с сабкомпонентами вносит путаницу подключение сабкомпонентов через модули в основной компонент и в java(generated) не генерится все в одном компоненте.

2023-01-07 19:24 UTC, antonkazakov requested changes
Привет. Оставил несколько маленьких замечаний

2023-01-07 19:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +    lateinit var producerComponent: FragmentProducerComponent
А зачем эта проперти

2023-01-07 19:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +        Log.v("sflow", "hash ${viewModelProducer.mutableStateFlow.hashCode()}")
Убери)

2023-01-07 19:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiver.kt
> +    lateinit var receiverComponent: FragmentReceiverComponent
Тоже можно убрать

2023-01-07 19:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiver.kt
> +        receiverComponent = DaggerFragmentReceiverComponent
Я бы перенес создание компонента в onCreate. Вызывается раньше и реже

2023-01-21 08:15 UTC, antonkazakov commented
👍

2023-01-21 08:15 UTC, closed without merging