dagger homework
Otus-Android/Dagger2Homework pull request #73
Opened 2023-02-09 09:00 UTC by nikman

2023-02-19 10:30 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний

2023-02-19 10:30 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityModule.kt
> +class MainActivityModule {
Тебе не нужен модуль, просто аннотацию скоупа повесь над EventBus

2023-02-19 10:30 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
>      private val context: Context
Если у тебя ViewModelProducer станет androidx.lifecycle.ViewModel, то может утечь активити

2023-02-19 10:30 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +                               private val context: Context) :
А почему ты в фабрику не инжектишь ничего и вручную создаешь

2023-02-19 21:49 UTC, nikman commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
>      private val context: Context
ViewModelReciever - поменял, унаследовал от AndroidViewModel. Как быть с ViewModelProducer? Корректно ли унаследовать его тоже от AndroidViewModel? Не очень понимаю как в таком случае быть с Application в конструкторе AndroidViewModel, если во ViewModelProducer нужен контекст Activity.

2023-02-19 21:50 UTC, nikman commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityModule.kt
> +class MainActivityModule {
Действительно, поправил.

2023-02-19 21:50 UTC, nikman commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +                               private val context: Context) :
Поправил.

2023-07-23 19:20 UTC, antonkazakov commented
👍

2023-07-23 19:20 UTC, closed without merging