V.Petrov, Dagger2 Homework
Otus-Android/Dagger2Homework pull request #75
Opened 2023-02-09 14:54 UTC by flyingV805

2023-02-19 15:24 UTC, antonkazakov requested changes
Привет. Оставил пару замечаний

2023-02-19 15:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    @Provides
Замени на Binds, это намного эффективнее

2023-02-19 15:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +@Module(subcomponents = [FragmentProducerComponent::class])
А почему только один компонент тут?

2023-02-19 15:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/ApplicationComponent.kt
> +    fun provideContext(): Context
А зачем тебе этот метод? Ты же сабкомпоненты выбрал, они и без этого увидят сущности которые провайдят комопненты выше

2023-02-19 15:24 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +): ViewModel() {
В таком случае здесь может быть утечка памяти, потому что ViewModel живет дольше чем активити

2023-02-20 03:53 UTC, flyingV805 commented on app/src/main/java/ru/otus/daggerhomework/di/ApplicationComponent.kt
> +    fun provideContext(): Context
Вашу логику понимаю, однако без этого метода, граф не собирается т.к. 

error: [Dagger/MissingBinding] @javax.inject.Named("appContext") android.content.Context cannot be provided without an @Provides-annotated method.
public abstract interface MainActivityComponent {
                ^
      @javax.inject.Named("appContext") android.content.Context is injected at
          ru.otus.daggerhomework.di.ViewModelModule.provideReceiverVM(context, �)
      ru.otus.daggerhomework.ViewModelReceiver is injected at
          ru.otus.daggerhomework.FragmentReceiver.viewModel
      ru.otus.daggerhomework.FragmentReceiver is injected at
          ru.otus.daggerhomework.di.FragmentReceiverComponent.inject(ru.otus.daggerhomework.FragmentReceiver) [ru.otus.daggerhomework.di.MainActivityComponent ? ru.otus.daggerhomework.di.FragmentReceiverComponent]

2023-02-20 03:53 UTC, flyingV805 commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityComponent.kt
> +    @Provides
Согласен, невнимательность

2023-03-18 17:39 UTC, closed without merging