Dagger 2 Homework (Teplitskaia)
Otus-Android/Dagger2Homework pull request #82
Opened 2023-05-12 15:25 UTC by xlnk

2023-05-28 12:37 UTC, antonkazakov requested changes
Оставил пару комментариев

2023-05-28 12:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/MainActivityScope.kt
> +annotation class MainActivityScope
Зачем под конкретный активити скоуп? Может лучше назвать ActivityScope

2023-05-28 12:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/EventModule.kt
> + * Модуль подключен в ApplicationComponent, так как используется Jetpack ViewModel [ViewModelReceiver]
По имплементации модуля я не вижу что он использует Вьюмодель.
Правильнее все таки его прилепить к Активити. В апликешйене это не нужно

2023-05-28 12:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +) : ViewModel() {
Так тут тоже можно убрать ViewModel

2023-05-28 12:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiverComponent.kt
> +    fun viewModelReceiver(): ViewModelReceiver.Factory
А зачем этот метод?

2023-05-28 12:37 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/App.kt
> +        applicationComponent
Это нужно?

2023-05-31 08:51 UTC, xlnk commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiverComponent.kt
> +    fun viewModelReceiver(): ViewModelReceiver.Factory
```kotlin
    private val selfViewModel: ViewModelReceiver by viewModels {
        AssistedViewModelFactory { fragmentReceiverComponent.viewModelReceiver().create() }
    }
```
Оно нужно для ViewModelProvider.Factory. Чтобы  ViewModelReceiver привязалась к ViewModelStore

2023-05-31 08:57 UTC, xlnk commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReceiver.kt
> +) : ViewModel() {
Его нельзя будет убрать так как его нельзя будет поместить в ViewModelStore

2023-05-31 08:58 UTC, xlnk commented on app/src/main/java/ru/otus/daggerhomework/di/EventModule.kt
> + * Модуль подключен в ApplicationComponent, так как используется Jetpack ViewModel [ViewModelReceiver]
```kotlin
class FragmentReceiver : Fragment() {
    private val selfViewModel: ViewModelReceiver by viewModels {
        AssistedViewModelFactory { fragmentReceiverComponent.viewModelReceiver().create() }
    }
 ```
 ```kotlin
class AssistedViewModelFactory<T: ViewModel>(
    private val factory: () -> T
) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        @Suppress("UNCHECKED_CAST")
        return factory.invoke() as T
    }
}
```

2023-05-31 09:49 UTC, xlnk commented on app/src/main/java/ru/otus/daggerhomework/di/EventModule.kt
> + * Модуль подключен в ApplicationComponent, так как используется Jetpack ViewModel [ViewModelReceiver]
Я еще добавила использование SavedStateHandle

2023-06-29 18:04 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentReceiverComponent.kt
> +    fun viewModelReceiver(): ViewModelReceiver.Factory
Тебе не нужно их наследовать от android.ViewModel

2023-06-29 18:05 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/di/EventModule.kt
> + * Модуль подключен в ApplicationComponent, так как используется Jetpack ViewModel [ViewModelReceiver]
Ну а что тебе мешает сделать свой скоуп и его вручную обрабатывать?

2023-07-18 13:18 UTC, xlnk commented on app/src/main/java/ru/otus/daggerhomework/di/EventModule.kt
> + * Модуль подключен в ApplicationComponent, так как используется Jetpack ViewModel [ViewModelReceiver]
я сделала ViewModelReceiverScope

2023-07-23 20:02 UTC, closed without merging