Зацепин Dagger2Homework
Otus-Android/Dagger2Homework pull request #84
Opened 2023-05-18 16:13 UTC by Zats1954

2023-06-04 07:32 UTC, antonkazakov requested changes
Привет. Оставил пару комментов

2023-06-04 07:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ApplicationComponent.kt
> +@Component()
Отформатируй код пожалуйста.
Скобки не нужны, лайнбрейк тоже

2023-06-04 07:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ColorGenerator.kt
> +class ColorGeneratorImpl @Inject constructor() : ColorGenerator {
Отформатируй

2023-06-04 07:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +        DaggerViewModelProducerComponent
onCreateView слишком часто вызывается, лучше перенести в oncreate/onattach

2023-06-04 07:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/FragmentProducer.kt
> +    lateinit var viewModelProducer: ViewModelProducer
Нельзя напрямую инжектить ViewModel. Их нужно создавать через фабрики, если у них не дефолтный конструктор

2023-06-04 07:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/MainActivity.kt
> +interface MainActivityComponent {
Тебе нужно в этот компонент положить какой то обсервер, и использовать его в двух дочерних компонентах

2023-06-04 07:32 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelReciever.kt
> +interface ViewModelReceiverComponent {
Вынеси компоненты/модули в отдельные файлы

2024-02-10 20:34 UTC, Zats1954 commented
.

2024-02-18 08:41 UTC, antonkazakov requested changes

2024-02-18 08:41 UTC, antonkazakov commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +    private val context: Context
Тут нужно как то обработать сиутацию чтобы не было утечки контекста. Тк ВМ живет дольше активити и хранит ссылку. Можешь просто убрать наследование от ViewModel

2024-03-06 19:25 UTC, Zats1954 commented on app/src/main/java/ru/otus/daggerhomework/ViewModelProducer.kt
> +    private val context: Context
Добавил WeakPreference

2024-03-17 08:06 UTC, closed without merging